apiVersion: v1
kind: Pod
spec:
  containers:
    - name: hugo
      image: cibuilds/hugo:0.72
      resources:
        requests:
          cpu: 1
      command:
      - cat
      tty: true
      securityContext:
        runAsUser: 0
        privileged: true
    - name: awscli
      image: amazon/aws-cli
      command:
      - cat
      tty: true
  imagePullSecrets:
    - name: dockerhub
  nodeSelector:
    instance-type: spot
